apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: phenovar-reset-state-entrypoint
    options:
      disableNameSuffixHash: true
    files:
      - entrypoint.sh

resources:
  - job.yml