tls_server_config:
  cert_file: /etc/pushgateway/tls/server.crt
  key_file: /etc/pushgateway/tls/server.key
  client_auth_type: RequireAndVerifyClientCert
  client_ca_file: /etc/pushgateway/tls/ca.crt