apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: prometheus-pushgateway-entrypoint
    options:
      disableNameSuffixHash: true
    files:
      - entrypoint.sh
  - name: prometheus-pushgateway-config
    options:
      disableNameSuffixHash: true
    files:
      - config.yml


resources:
  - deployment.yml
  - service.yml