apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: upsert-phenovar-token-script
    options:
      disableNameSuffixHash: true
    files:
      - upsert-phenovar-token.sh

resources:
  - cron-job.yml