---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: phenovar-server
  name: phenovar-server
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: phenovar
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: phenovar-file-server
  name: phenovar-file-server
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: phenovar
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: phenovar-flower-server
  name: phenovar-flower-server
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: phenovar